name: CI

on: [push]

jobs:
  build-test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node_version: [8,10]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: install packages
      run: npm install
    - name: build
      run: npm run release
    - name: test
      run: npm run test
