name: CI

on: [push]

jobs:
  build-test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node_version: [8,10]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: npm ci
      run: npm ci
    - name: build
      run: npm run release
    - name: test
      run: npm run test
